global using MPay.API.Endpoints;
global using MPay.Core;
global using MPay.Core.DTO;
global using MPay.Core.Services;
global using MPay.Infrastructure;
global using MPay.Infrastructure.DAL;
global using MPay.Infrastructure.Exceptions;
global using MPay.Infrastructure.Validation;
global using MPay.Infrastructure.Services;